replicaCount: 1

quarkusDefaults:
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "1Gi"
      cpu: "500m"

strimzi:
  enabled: true

kafka:
  enabled: true
  name: dev-kafka
  version: "3.9.1"
  topic: handlaggning-done


quarkus:
  - name: folkbokford
    image:
      repository: ghcr.io/forsakringskassan/folkbokford
      tag: 0.2.5
    waitForKafka: false
  - name: arbetsgivare
    image:
      repository: ghcr.io/forsakringskassan/arbetsgivare
      tag: 0.2.2
    waitForKafka: false
  - name: erbjudande
    image:
      repository: ghcr.io/forsakringskassan/rimfrost-service-erbjudande
      tag: 0.0.1
    waitForKafka: false
  - name: referensdata
    image:
      repository: ghcr.io/forsakringskassan/rimfrost-service-referensdata
      tag: 0.0.2
    waitForKafka: false
  - name: uppgiftslager
    image:
      repository: ghcr.io/forsakringskassan/rimfrost-operativt-uppgiftslager
      tag: 0.2.6
    env:
      - name: MP_MESSAGING_CONNECTOR_SMALLRYE_KAFKA_BOOTSTRAP_SERVERS
        value: "dev-kafka-kafka-bootstrap:9092"
      - name: MP_MESSAGING_CONNECTOR_SMALLRYE_KAFKA_ALLOW_AUTO_CREATE_TOPICS
        value: "true"
    waitForKafka: true
  - name: vah
    image:
      repository: ghcr.io/forsakringskassan/rimfrost-vard-av-husdjur
      tag: 0.1.4
    env:
      - name: MP_MESSAGING_CONNECTOR_SMALLRYE_KAFKA_BOOTSTRAP_SERVERS
        value: "dev-kafka-kafka-bootstrap:9092"
      - name: MP_MESSAGING_CONNECTOR_SMALLRYE_KAFKA_ALLOW_AUTO_CREATE_TOPICS
        value: "true"
    waitForKafka: true
  - name: rtf-maskinell
    image:
      repository: ghcr.io/forsakringskassan/rimfrost-regel-rtf-maskinell
      tag: 0.5.4
    env:
      - name: MP_MESSAGING_CONNECTOR_SMALLRYE_KAFKA_BOOTSTRAP_SERVERS
        value: "dev-kafka-kafka-bootstrap:9092"
      - name: MP_MESSAGING_CONNECTOR_SMALLRYE_KAFKA_ALLOW_AUTO_CREATE_TOPICS
        value: "true"
    waitForKafka: true
  - name: rtf-manuell
    image:
      repository: ghcr.io/forsakringskassan/rimfrost-regel-rtf-manuell
      tag: 0.4.6
      #repository: rimfrost/rimfrost-regel-rtf-manuell
      #tag: latest
      #pullPolicy: Never
    env:
      - name: MP_MESSAGING_CONNECTOR_SMALLRYE_KAFKA_BOOTSTRAP_SERVERS
        value: "dev-kafka-kafka-bootstrap:9092"
      - name: MP_MESSAGING_CONNECTOR_SMALLRYE_KAFKA_ALLOW_AUTO_CREATE_TOPICS
        value: "true"
      - name: JAVA_TOOL_OPTIONS
        value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    waitForKafka: true
  - name: bekraftabeslut
    image:
      repository: ghcr.io/forsakringskassan/rimfrost-regel-bekraftabeslut
      tag: 0.0.10
    env:
      - name: MP_MESSAGING_CONNECTOR_SMALLRYE_KAFKA_BOOTSTRAP_SERVERS
        value: "dev-kafka-kafka-bootstrap:9092"
      - name: MP_MESSAGING_CONNECTOR_SMALLRYE_KAFKA_ALLOW_AUTO_CREATE_TOPICS
        value: "true"
    waitForKafka: true
  - name: handlaggning
    image:
      repository: ghcr.io/forsakringskassan/rimfrost-service-handlaggning
      tag: 0.3.1
    env:
      - name: MP_MESSAGING_CONNECTOR_SMALLRYE_KAFKA_BOOTSTRAP_SERVERS
        value: "dev-kafka-kafka-bootstrap:9092"
      - name: MP_MESSAGING_CONNECTOR_SMALLRYE_KAFKA_ALLOW_AUTO_CREATE_TOPICS
        value: "true"
    waitForKafka: true

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
  hosts:
    - paths:
        - path: /api
          pathType: Prefix
          backend: quarkus
