{{- if .Values.strimzi.enabled }}
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-kafka
spec:
  kafka:
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    config:
      auto.create.topics.enable: "true"
      num.partitions: 1
      default.replication.factor: 1
    storage: { type: ephemeral }
  zookeeper:
    replicas: 1
    storage: { type: ephemeral }
  entityOperator:
    topicOperator: {}
    userOperator: {}
{{- end }}