apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-kafka-cluster
spec:
  kafka:
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    storage:
      type: ephemeral
    config:
      process.roles: broker,controller
      node.id: 0
      controller.listener.names: CONTROLLER
      controller.quorum.voters: "0@my-kafkacluster-kafka-0.my-kafkacluster-kafka-brokers.kafka.svc:9093"
      inter.broker.listener.name: PLAINTEXT
      num.partitions: 1
      default.replication.factor: 1
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1

  entityOperator:
    topicOperator: {}
    userOperator: {}
